name: CI
on:
  push:
    branches-ignore:
      - 'generated'
      - 'codegen/**'
      - 'integrated/**'
      - 'stl-preview-head/**'
      - 'stl-preview-base/**'
  pull_request:
    branches-ignore:
      - 'stl-preview-head/**'
      - 'stl-preview-base/**'

jobs:
  lint:
    timeout-minutes: 10
    name: lint
    runs-on: ${{ github.repository == 'stainless-sdks/privy-api-client-go' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork

    steps:
      - uses: actions/checkout@v6

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Run lints
        run: ./scripts/lint
  test:
    timeout-minutes: 10
    env:
      TEST_APP_SECRET: ${{ secrets.TEST_APP_SECRET }}
      JWT_AUTH_SK: ${{ secrets.JWT_AUTH_SK }}
      P256_PRIVATE_KEY: ${{ secrets.P256_PRIVATE_KEY }}
      TEST_APP_ID: ${{ secrets.TEST_APP_ID }}
      TEST_API_URL: ${{ secrets.TEST_API_URL }}
      JWT_AUTH_SUBJECT: ${{ secrets.JWT_AUTH_SUBJECT }}
      P256_PUBLIC_KEY: ${{ secrets.P256_PUBLIC_KEY }}
      OWNERLESS_ETHEREUM_WALLET_ID: ${{ secrets.OWNERLESS_ETHEREUM_WALLET_ID }}
      OWNERLESS_ETHEREUM_WALLET_ADDRESS: ${{ secrets.OWNERLESS_ETHEREUM_WALLET_ADDRESS }}
      P256_OWNED_ETHEREUM_WALLET_ID: ${{ secrets.P256_OWNED_ETHEREUM_WALLET_ID }}
      P256_OWNED_ETHEREUM_WALLET_ADDRESS: ${{ secrets.P256_OWNED_ETHEREUM_WALLET_ADDRESS }}
      USER_OWNED_ETHEREUM_WALLET_ID: ${{ secrets.USER_OWNED_ETHEREUM_WALLET_ID }}
      USER_OWNED_ETHEREUM_WALLET_ADDRESS: ${{ secrets.USER_OWNED_ETHEREUM_WALLET_ADDRESS }}
      OWNERLESS_SOLANA_WALLET_ID: ${{ secrets.OWNERLESS_SOLANA_WALLET_ID }}
      OWNERLESS_SOLANA_WALLET_ADDRESS: ${{ secrets.OWNERLESS_SOLANA_WALLET_ADDRESS }}
      OWNERLESS_SOLANA_WALLET_PUBLIC_KEY: ${{ secrets.OWNERLESS_SOLANA_WALLET_PUBLIC_KEY }}
      P256_OWNED_SOLANA_WALLET_ID: ${{ secrets.P256_OWNED_SOLANA_WALLET_ID }}
      P256_OWNED_SOLANA_WALLET_ADDRESS: ${{ secrets.P256_OWNED_SOLANA_WALLET_ADDRESS }}
      P256_OWNED_SOLANA_WALLET_PUBLIC_KEY: ${{ secrets.P256_OWNED_SOLANA_WALLET_PUBLIC_KEY }}
      USER_OWNED_SOLANA_WALLET_ID: ${{ secrets.USER_OWNED_SOLANA_WALLET_ID }}
      USER_OWNED_SOLANA_WALLET_ADDRESS: ${{ secrets.USER_OWNED_SOLANA_WALLET_ADDRESS }}
      USER_OWNED_SOLANA_WALLET_PUBLIC_KEY: ${{ secrets.USER_OWNED_SOLANA_WALLET_PUBLIC_KEY }}
      OWNERLESS_TRON_WALLET_ID: ${{ secrets.OWNERLESS_TRON_WALLET_ID }}
      OWNERLESS_TRON_WALLET_ADDRESS: ${{ secrets.OWNERLESS_TRON_WALLET_ADDRESS }}
      OWNERLESS_TRON_WALLET_PK: ${{ secrets.OWNERLESS_TRON_WALLET_PK }}
      P256_OWNED_TRON_WALLET_ID: ${{ secrets.P256_OWNED_TRON_WALLET_ID }}
      P256_OWNED_TRON_WALLET_ADDRESS: ${{ secrets.P256_OWNED_TRON_WALLET_ADDRESS }}
      P256_OWNED_TRON_WALLET_PK: ${{ secrets.P256_OWNED_TRON_WALLET_PK }}
    name: test
    runs-on: ${{ github.repository == 'stainless-sdks/privy-api-client-go' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v6

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Bootstrap
        run: ./scripts/bootstrap

      - name: Run tests
        run: go test ./e2e/... -v
